user nobody nogroup;
worker_processes auto;
pid /tmp/nginx.pid;
events {
  worker_connections 512;
}
http {
  include /etc/nginx/mime.types;
  client_max_body_size 50M;
  client_body_temp_path /tmp/client_body;
  fastcgi_temp_path /tmp/fastcgi_temp;
  proxy_temp_path /tmp/proxy_temp;
  scgi_temp_path /tmp/scgi_temp;
  uwsgi_temp_path /tmp/uwsgi_temp;

  server {
    listen ${{PORT}};
    server_name _;
    root /app/public;
    index index.php index.html index.htm;
    
    location / {
      try_files $uri $uri/ /index.php?$query_string;
    }
    
    location ~ \.php$ {
      fastcgi_pass 127.0.0.1:9000;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      include fastcgi_params;
    }
  }
}
