[build]
builder = "NIXPACKS"
buildCommand = "npm run build && php artisan storage:link"

[build.env]
COMPOSER_MEMORY_LIMIT = "-1"

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20"]

# Force new Railway deployment queue
